//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace POCDriverApp.Entity
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:posten.no/eConnect/OperationList")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:posten.no/eConnect/OperationList", IsNullable = false)]
    public partial class OperationList
    {

        private string userLogonIdField;

        private System.DateTime lastChangedField;

        private string operationListIdField;

        private string listTypeField;

        private string versionNumberField;

        private OperationListLoadCarrier[] loadCarrierField;

        private string[] deletedStopsField;

        private OperationListStop[] stopField;

        private StopType repositionedStopField;

        private string[] deletedOrdersField;

        private string listInformationField;

        private string sessionIdField;

        private string correlationIdField;

        private string captureEquipmentIdField;

        /// <remarks/>
        public string UserLogonId
        {
            get
            {
                return this.userLogonIdField;
            }
            set
            {
                this.userLogonIdField = value;
            }
        }

        /// <remarks/>
        public System.DateTime LastChanged
        {
            get
            {
                return this.lastChangedField;
            }
            set
            {
                this.lastChangedField = value;
            }
        }

        /// <remarks/>
        public string OperationListId
        {
            get
            {
                return this.operationListIdField;
            }
            set
            {
                this.operationListIdField = value;
            }
        }

        /// <remarks/>
        public string ListType
        {
            get
            {
                return this.listTypeField;
            }
            set
            {
                this.listTypeField = value;
            }
        }

        /// <remarks/>
        public string VersionNumber
        {
            get
            {
                return this.versionNumberField;
            }
            set
            {
                this.versionNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LoadCarrier")]
        public OperationListLoadCarrier[] LoadCarrier
        {
            get
            {
                return this.loadCarrierField;
            }
            set
            {
                this.loadCarrierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("StopId", IsNullable = false)]
        public string[] DeletedStops
        {
            get
            {
                return this.deletedStopsField;
            }
            set
            {
                this.deletedStopsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Stop")]
        public OperationListStop[] Stop
        {
            get
            {
                return this.stopField;
            }
            set
            {
                this.stopField = value;
            }
        }

        /// <remarks/>
        public StopType RepositionedStop
        {
            get
            {
                return this.repositionedStopField;
            }
            set
            {
                this.repositionedStopField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("OrderID", IsNullable = false)]
        public string[] DeletedOrders
        {
            get
            {
                return this.deletedOrdersField;
            }
            set
            {
                this.deletedOrdersField = value;
            }
        }

        /// <remarks/>
        public string ListInformation
        {
            get
            {
                return this.listInformationField;
            }
            set
            {
                this.listInformationField = value;
            }
        }

        /// <remarks/>
        public string SessionId
        {
            get
            {
                return this.sessionIdField;
            }
            set
            {
                this.sessionIdField = value;
            }
        }

        /// <remarks/>
        public string CorrelationId
        {
            get
            {
                return this.correlationIdField;
            }
            set
            {
                this.correlationIdField = value;
            }
        }

        /// <remarks/>
        public string CaptureEquipmentId
        {
            get
            {
                return this.captureEquipmentIdField;
            }
            set
            {
                this.captureEquipmentIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:posten.no/eConnect/OperationList")]
    public partial class OperationListLoadCarrier
    {

        private string loadCarrierIdField;

        private bool hasPowerField;

        public OperationListLoadCarrier()
        {
            this.loadCarrierIdField = "true";
        }

        /// <remarks/>
        public string LoadCarrierId
        {
            get
            {
                return this.loadCarrierIdField;
            }
            set
            {
                this.loadCarrierIdField = value;
            }
        }

        /// <remarks/>
        public bool HasPower
        {
            get
            {
                return this.hasPowerField;
            }
            set
            {
                this.hasPowerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:posten.no/eConnect/OperationList")]
    public partial class PdaSignature
    {

        private string consigneeNameField;

        private string signatureTimeField;

        private string graphicalSignatureField;

        /// <remarks/>
        public string ConsigneeName
        {
            get
            {
                return this.consigneeNameField;
            }
            set
            {
                this.consigneeNameField = value;
            }
        }

        /// <remarks/>
        public string SignatureTime
        {
            get
            {
                return this.signatureTimeField;
            }
            set
            {
                this.signatureTimeField = value;
            }
        }

        /// <remarks/>
        public string GraphicalSignature
        {
            get
            {
                return this.graphicalSignatureField;
            }
            set
            {
                this.graphicalSignatureField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:posten.no/eConnect/OperationList")]
    public partial class PdaVas
    {

        private string orderIdField;

        private string orderStopIdField;

        private string vasIdField;

        private string vasTypeIdField;

        private string vasTypeField;

        private string amountField;

        private string extraInfoField;

        private string creatorField;

        private System.DateTime creationDateField;

        private bool signatureRequiredField;

        private PdaSignature signatureField;

        /// <remarks/>
        public string OrderId
        {
            get
            {
                return this.orderIdField;
            }
            set
            {
                this.orderIdField = value;
            }
        }

        /// <remarks/>
        public string OrderStopId
        {
            get
            {
                return this.orderStopIdField;
            }
            set
            {
                this.orderStopIdField = value;
            }
        }

        /// <remarks/>
        public string VasId
        {
            get
            {
                return this.vasIdField;
            }
            set
            {
                this.vasIdField = value;
            }
        }

        /// <remarks/>
        public string VasTypeId
        {
            get
            {
                return this.vasTypeIdField;
            }
            set
            {
                this.vasTypeIdField = value;
            }
        }

        /// <remarks/>
        public string VasType
        {
            get
            {
                return this.vasTypeField;
            }
            set
            {
                this.vasTypeField = value;
            }
        }

        /// <remarks/>
        public string Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        public string ExtraInfo
        {
            get
            {
                return this.extraInfoField;
            }
            set
            {
                this.extraInfoField = value;
            }
        }

        /// <remarks/>
        public string Creator
        {
            get
            {
                return this.creatorField;
            }
            set
            {
                this.creatorField = value;
            }
        }

        /// <remarks/>
        public System.DateTime CreationDate
        {
            get
            {
                return this.creationDateField;
            }
            set
            {
                this.creationDateField = value;
            }
        }

        /// <remarks/>
        public bool SignatureRequired
        {
            get
            {
                return this.signatureRequiredField;
            }
            set
            {
                this.signatureRequiredField = value;
            }
        }

        /// <remarks/>
        public PdaSignature Signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:posten.no/eConnect/OperationList")]
    public partial class PdaGoods
    {

        private string orderIDField;

        private string productField;

        private string specificationField;

        private string loadCarrierField;

        private string noOfUnitsField;

        private string weightField;

        private string volumeField;

        /// <remarks/>
        public string OrderID
        {
            get
            {
                return this.orderIDField;
            }
            set
            {
                this.orderIDField = value;
            }
        }

        /// <remarks/>
        public string Product
        {
            get
            {
                return this.productField;
            }
            set
            {
                this.productField = value;
            }
        }

        /// <remarks/>
        public string Specification
        {
            get
            {
                return this.specificationField;
            }
            set
            {
                this.specificationField = value;
            }
        }

        /// <remarks/>
        public string LoadCarrier
        {
            get
            {
                return this.loadCarrierField;
            }
            set
            {
                this.loadCarrierField = value;
            }
        }

        /// <remarks/>
        public string NoOfUnits
        {
            get
            {
                return this.noOfUnitsField;
            }
            set
            {
                this.noOfUnitsField = value;
            }
        }

        /// <remarks/>
        public string Weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }

        /// <remarks/>
        public string Volume
        {
            get
            {
                return this.volumeField;
            }
            set
            {
                this.volumeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:posten.no/eConnect/OperationList")]
    public partial class PdaDeviation
    {

        private string orderIDField;

        private string orderStopIDField;

        private string typeIdField;

        private string causeIdField;

        private string actionIdField;

        private string causeField;

        private string actionField;

        private string extraInfoField;

        private System.DateTime creationDateField;

        /// <remarks/>
        public string OrderID
        {
            get
            {
                return this.orderIDField;
            }
            set
            {
                this.orderIDField = value;
            }
        }

        /// <remarks/>
        public string OrderStopID
        {
            get
            {
                return this.orderStopIDField;
            }
            set
            {
                this.orderStopIDField = value;
            }
        }

        /// <remarks/>
        public string TypeId
        {
            get
            {
                return this.typeIdField;
            }
            set
            {
                this.typeIdField = value;
            }
        }

        /// <remarks/>
        public string CauseId
        {
            get
            {
                return this.causeIdField;
            }
            set
            {
                this.causeIdField = value;
            }
        }

        /// <remarks/>
        public string ActionId
        {
            get
            {
                return this.actionIdField;
            }
            set
            {
                this.actionIdField = value;
            }
        }

        /// <remarks/>
        public string Cause
        {
            get
            {
                return this.causeField;
            }
            set
            {
                this.causeField = value;
            }
        }

        /// <remarks/>
        public string Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        /// <remarks/>
        public string ExtraInfo
        {
            get
            {
                return this.extraInfoField;
            }
            set
            {
                this.extraInfoField = value;
            }
        }

        /// <remarks/>
        public System.DateTime CreationDate
        {
            get
            {
                return this.creationDateField;
            }
            set
            {
                this.creationDateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:posten.no/eConnect/OperationList")]
    public partial class ConsignmentItemType
    {

        private string consignmentItemNumberField;

        private MeasureType weightField;

        private MeasureType volumeField;

        /// <remarks/>
        public string ConsignmentItemNumber
        {
            get
            {
                return this.consignmentItemNumberField;
            }
            set
            {
                this.consignmentItemNumberField = value;
            }
        }

        /// <remarks/>
        public MeasureType Weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }

        /// <remarks/>
        public MeasureType Volume
        {
            get
            {
                return this.volumeField;
            }
            set
            {
                this.volumeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:posten.no/eConnect/OperationList")]
    public partial class MeasureType
    {

        private string measureUnitField;

        private decimal amountField;

        /// <remarks/>
        public string MeasureUnit
        {
            get
            {
                return this.measureUnitField;
            }
            set
            {
                this.measureUnitField = value;
            }
        }

        /// <remarks/>
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:posten.no/eConnect/OperationList")]
    public partial class ConsigneeType
    {

        private string name1Field;

        private string name2Field;

        private string address1Field;

        private string address2Field;

        private string postalCodeField;

        private string postalNameField;

        private string countryCodeField;

        private string deliveryAddress1Field;

        private string deliveryAddress2Field;

        private string deliveryPostalCodeField;

        private string deliveryPostalNameField;

        private string deliveryCountryCodeField;

        private string contactPersonField;

        private string phoneNumberField;

        /// <remarks/>
        public string Name1
        {
            get
            {
                return this.name1Field;
            }
            set
            {
                this.name1Field = value;
            }
        }

        /// <remarks/>
        public string Name2
        {
            get
            {
                return this.name2Field;
            }
            set
            {
                this.name2Field = value;
            }
        }

        /// <remarks/>
        public string Address1
        {
            get
            {
                return this.address1Field;
            }
            set
            {
                this.address1Field = value;
            }
        }

        /// <remarks/>
        public string Address2
        {
            get
            {
                return this.address2Field;
            }
            set
            {
                this.address2Field = value;
            }
        }

        /// <remarks/>
        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }

        /// <remarks/>
        public string PostalName
        {
            get
            {
                return this.postalNameField;
            }
            set
            {
                this.postalNameField = value;
            }
        }

        /// <remarks/>
        public string CountryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }

        /// <remarks/>
        public string DeliveryAddress1
        {
            get
            {
                return this.deliveryAddress1Field;
            }
            set
            {
                this.deliveryAddress1Field = value;
            }
        }

        /// <remarks/>
        public string DeliveryAddress2
        {
            get
            {
                return this.deliveryAddress2Field;
            }
            set
            {
                this.deliveryAddress2Field = value;
            }
        }

        /// <remarks/>
        public string DeliveryPostalCode
        {
            get
            {
                return this.deliveryPostalCodeField;
            }
            set
            {
                this.deliveryPostalCodeField = value;
            }
        }

        /// <remarks/>
        public string DeliveryPostalName
        {
            get
            {
                return this.deliveryPostalNameField;
            }
            set
            {
                this.deliveryPostalNameField = value;
            }
        }

        /// <remarks/>
        public string DeliveryCountryCode
        {
            get
            {
                return this.deliveryCountryCodeField;
            }
            set
            {
                this.deliveryCountryCodeField = value;
            }
        }

        /// <remarks/>
        public string ContactPerson
        {
            get
            {
                return this.contactPersonField;
            }
            set
            {
                this.contactPersonField = value;
            }
        }

        /// <remarks/>
        public string PhoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:posten.no/eConnect/OperationList")]
    public partial class ConsignorType
    {

        private string name1Field;

        private string name2Field;

        private string address1Field;

        private string address2Field;

        private string postalCodeField;

        private string postalNameField;

        private string countryCodeField;

        private string contactPersonField;

        private string phoneNumberField;

        /// <remarks/>
        public string Name1
        {
            get
            {
                return this.name1Field;
            }
            set
            {
                this.name1Field = value;
            }
        }

        /// <remarks/>
        public string Name2
        {
            get
            {
                return this.name2Field;
            }
            set
            {
                this.name2Field = value;
            }
        }

        /// <remarks/>
        public string Address1
        {
            get
            {
                return this.address1Field;
            }
            set
            {
                this.address1Field = value;
            }
        }

        /// <remarks/>
        public string Address2
        {
            get
            {
                return this.address2Field;
            }
            set
            {
                this.address2Field = value;
            }
        }

        /// <remarks/>
        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }

        /// <remarks/>
        public string PostalName
        {
            get
            {
                return this.postalNameField;
            }
            set
            {
                this.postalNameField = value;
            }
        }

        /// <remarks/>
        public string CountryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }

        /// <remarks/>
        public string ContactPerson
        {
            get
            {
                return this.contactPersonField;
            }
            set
            {
                this.contactPersonField = value;
            }
        }

        /// <remarks/>
        public string PhoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:posten.no/eConnect/OperationList")]
    public partial class TransportEquipmentType
    {

        private string typeField;

        private short numberOfField;

        /// <remarks/>
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public short NumberOf
        {
            get
            {
                return this.numberOfField;
            }
            set
            {
                this.numberOfField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:posten.no/eConnect/OperationList")]
    public partial class PackageTypeType
    {

        private string typeField;

        private short numberOfField;

        /// <remarks/>
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public short NumberOf
        {
            get
            {
                return this.numberOfField;
            }
            set
            {
                this.numberOfField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:posten.no/eConnect/OperationList")]
    public partial class PlannedConsignmentsType
    {

        private string orderNumberField;

        private string customerIdField;

        private string consignmentNumberField;

        private string productIdField;

        private string productCategoryField;

        private PackageTypeType[] packageTypeField;

        private TransportEquipmentType[] transportEquipmentField;

        private ConsignorType consignorField;

        private ConsigneeType consigneeField;

        private MeasureType weightField;

        private MeasureType volumeField;

        private int consignmentItemCountField;

        private bool consignmentItemCountFieldSpecified;

        private ConsignmentItemType[] consignmentItemField;

        private PlannedConsignmentsTypeShipment[] shipmentField;

        private OperationNoteTypeNote[] operationNotesField;

        /// <remarks/>
        public string OrderNumber
        {
            get
            {
                return this.orderNumberField;
            }
            set
            {
                this.orderNumberField = value;
            }
        }

        /// <remarks/>
        public string CustomerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }

        /// <remarks/>
        public string ConsignmentNumber
        {
            get
            {
                return this.consignmentNumberField;
            }
            set
            {
                this.consignmentNumberField = value;
            }
        }

        /// <remarks/>
        public string ProductId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }

        /// <remarks/>
        public string ProductCategory
        {
            get
            {
                return this.productCategoryField;
            }
            set
            {
                this.productCategoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PackageType")]
        public PackageTypeType[] PackageType
        {
            get
            {
                return this.packageTypeField;
            }
            set
            {
                this.packageTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TransportEquipment")]
        public TransportEquipmentType[] TransportEquipment
        {
            get
            {
                return this.transportEquipmentField;
            }
            set
            {
                this.transportEquipmentField = value;
            }
        }

        /// <remarks/>
        public ConsignorType Consignor
        {
            get
            {
                return this.consignorField;
            }
            set
            {
                this.consignorField = value;
            }
        }

        /// <remarks/>
        public ConsigneeType Consignee
        {
            get
            {
                return this.consigneeField;
            }
            set
            {
                this.consigneeField = value;
            }
        }

        /// <remarks/>
        public MeasureType Weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }

        /// <remarks/>
        public MeasureType Volume
        {
            get
            {
                return this.volumeField;
            }
            set
            {
                this.volumeField = value;
            }
        }

        /// <remarks/>
        public int ConsignmentItemCount
        {
            get
            {
                return this.consignmentItemCountField;
            }
            set
            {
                this.consignmentItemCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConsignmentItemCountSpecified
        {
            get
            {
                return this.consignmentItemCountFieldSpecified;
            }
            set
            {
                this.consignmentItemCountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConsignmentItem")]
        public ConsignmentItemType[] ConsignmentItem
        {
            get
            {
                return this.consignmentItemField;
            }
            set
            {
                this.consignmentItemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Shipment")]
        public PlannedConsignmentsTypeShipment[] Shipment
        {
            get
            {
                return this.shipmentField;
            }
            set
            {
                this.shipmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Note", IsNullable = false)]
        public OperationNoteTypeNote[] OperationNotes
        {
            get
            {
                return this.operationNotesField;
            }
            set
            {
                this.operationNotesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:posten.no/eConnect/OperationList")]
    public partial class PlannedConsignmentsTypeShipment
    {

        private string shipmentIdField;

        private string[] shipmentDetailIdField;

        /// <remarks/>
        public string ShipmentId
        {
            get
            {
                return this.shipmentIdField;
            }
            set
            {
                this.shipmentIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShipmentDetailId")]
        public string[] ShipmentDetailId
        {
            get
            {
                return this.shipmentDetailIdField;
            }
            set
            {
                this.shipmentDetailIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:posten.no/eConnect/OperationList")]
    public partial class OperationNoteTypeNote
    {

        private int lineNumberField;

        private string typeField;

        private string textField;

        public OperationNoteTypeNote()
        {
            this.lineNumberField = 1;
        }

        /// <remarks/>
        public int LineNumber
        {
            get
            {
                return this.lineNumberField;
            }
            set
            {
                this.lineNumberField = value;
            }
        }

        /// <remarks/>
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:posten.no/eConnect/OperationList")]
    public partial class PlannedOperationType
    {

        private string operationIdField;

        private PlannedOperationTypeOperationType operationTypeField;

        private bool operationSignatureRequiredField;

        private bool operationSignatureRequiredFieldSpecified;

        private string statusField;

        private string operationOriginField;

        private string pickupOrderNumberField;

        private System.DateTime earliestStartTimeField;

        private bool earliestStartTimeFieldSpecified;

        private System.DateTime latestStartTimeField;

        private bool latestStartTimeFieldSpecified;

        private int consignmentItemCountField;

        private bool consignmentItemCountFieldSpecified;

        private MeasureType weightField;

        private MeasureType volumeField;

        private string powerLoadCarrierIdField;

        private string loadCarrierIdField;

        private string tripIdField;

        private string routeField;

        private string externalTripIdField;

        private PlannedConsignmentsType[] plannedConsignmentsField;

        private PackageTypeType[] packageTypeField;

        private TransportEquipmentType[] transportEquipmentField;

        private bool repositioningField;

        private string serviceField;

        private OperationNoteTypeNote[] operationNotesField;

        private PdaDeviation[] deviationItemField;

        private string orderIDField;

        public PlannedOperationType()
        {
            this.repositioningField = false;
        }

        /// <remarks/>
        public string OperationId
        {
            get
            {
                return this.operationIdField;
            }
            set
            {
                this.operationIdField = value;
            }
        }

        /// <remarks/>
        public PlannedOperationTypeOperationType OperationType
        {
            get
            {
                return this.operationTypeField;
            }
            set
            {
                this.operationTypeField = value;
            }
        }

        /// <remarks/>
        public bool OperationSignatureRequired
        {
            get
            {
                return this.operationSignatureRequiredField;
            }
            set
            {
                this.operationSignatureRequiredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OperationSignatureRequiredSpecified
        {
            get
            {
                return this.operationSignatureRequiredFieldSpecified;
            }
            set
            {
                this.operationSignatureRequiredFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public string OperationOrigin
        {
            get
            {
                return this.operationOriginField;
            }
            set
            {
                this.operationOriginField = value;
            }
        }

        /// <remarks/>
        public string PickupOrderNumber
        {
            get
            {
                return this.pickupOrderNumberField;
            }
            set
            {
                this.pickupOrderNumberField = value;
            }
        }

        /// <remarks/>
        public System.DateTime EarliestStartTime
        {
            get
            {
                return this.earliestStartTimeField;
            }
            set
            {
                this.earliestStartTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EarliestStartTimeSpecified
        {
            get
            {
                return this.earliestStartTimeFieldSpecified;
            }
            set
            {
                this.earliestStartTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime LatestStartTime
        {
            get
            {
                return this.latestStartTimeField;
            }
            set
            {
                this.latestStartTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatestStartTimeSpecified
        {
            get
            {
                return this.latestStartTimeFieldSpecified;
            }
            set
            {
                this.latestStartTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int ConsignmentItemCount
        {
            get
            {
                return this.consignmentItemCountField;
            }
            set
            {
                this.consignmentItemCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConsignmentItemCountSpecified
        {
            get
            {
                return this.consignmentItemCountFieldSpecified;
            }
            set
            {
                this.consignmentItemCountFieldSpecified = value;
            }
        }

        /// <remarks/>
        public MeasureType Weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }

        /// <remarks/>
        public MeasureType Volume
        {
            get
            {
                return this.volumeField;
            }
            set
            {
                this.volumeField = value;
            }
        }

        /// <remarks/>
        public string PowerLoadCarrierId
        {
            get
            {
                return this.powerLoadCarrierIdField;
            }
            set
            {
                this.powerLoadCarrierIdField = value;
            }
        }

        /// <remarks/>
        public string LoadCarrierId
        {
            get
            {
                return this.loadCarrierIdField;
            }
            set
            {
                this.loadCarrierIdField = value;
            }
        }

        /// <remarks/>
        public string TripId
        {
            get
            {
                return this.tripIdField;
            }
            set
            {
                this.tripIdField = value;
            }
        }

        /// <remarks/>
        public string Route
        {
            get
            {
                return this.routeField;
            }
            set
            {
                this.routeField = value;
            }
        }

        /// <remarks/>
        public string ExternalTripId
        {
            get
            {
                return this.externalTripIdField;
            }
            set
            {
                this.externalTripIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PlannedConsignments")]
        public PlannedConsignmentsType[] PlannedConsignments
        {
            get
            {
                return this.plannedConsignmentsField;
            }
            set
            {
                this.plannedConsignmentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PackageType")]
        public PackageTypeType[] PackageType
        {
            get
            {
                return this.packageTypeField;
            }
            set
            {
                this.packageTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TransportEquipment")]
        public TransportEquipmentType[] TransportEquipment
        {
            get
            {
                return this.transportEquipmentField;
            }
            set
            {
                this.transportEquipmentField = value;
            }
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Repositioning
        {
            get
            {
                return this.repositioningField;
            }
            set
            {
                this.repositioningField = value;
            }
        }

        /// <remarks/>
        public string Service
        {
            get
            {
                return this.serviceField;
            }
            set
            {
                this.serviceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Note", IsNullable = false)]
        public OperationNoteTypeNote[] OperationNotes
        {
            get
            {
                return this.operationNotesField;
            }
            set
            {
                this.operationNotesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DeviationItem")]
        public PdaDeviation[] DeviationItem
        {
            get
            {
                return this.deviationItemField;
            }
            set
            {
                this.deviationItemField = value;
            }
        }

        /// <remarks/>
        public string OrderID
        {
            get
            {
                return this.orderIDField;
            }
            set
            {
                this.orderIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:posten.no/eConnect/OperationList")]
    public enum PlannedOperationTypeOperationType
    {

        /// <remarks/>
        PICKUP,

        /// <remarks/>
        LOAD_LINE_HAUL,

        /// <remarks/>
        LOAD_DISTRIBUTION,

        /// <remarks/>
        UNLOAD_LINE_HAUL,

        /// <remarks/>
        UNLOAD_PICKUP,

        /// <remarks/>
        DELIVERY,

        /// <remarks/>
        LOAD,

        /// <remarks/>
        UNLOAD,

        /// <remarks/>
        RETURNEDDELIVERY,

        ///when an operation has pickups more than one
        MULTIPLEPICKUP,

        ///when an operation has delivery more than one
        MULTIPLEDELIVERY
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:posten.no/eConnect/OperationList")]
    public partial class MapCoordinate
    {

        private string coordinateXField;

        private string coordinateYField;

        private string coordinateSystemField;

        /// <remarks/>
        public string CoordinateX
        {
            get
            {
                return this.coordinateXField;
            }
            set
            {
                this.coordinateXField = value;
            }
        }

        /// <remarks/>
        public string CoordinateY
        {
            get
            {
                return this.coordinateYField;
            }
            set
            {
                this.coordinateYField = value;
            }
        }

        /// <remarks/>
        public string CoordinateSystem
        {
            get
            {
                return this.coordinateSystemField;
            }
            set
            {
                this.coordinateSystemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:posten.no/eConnect/OperationList")]
    public partial class LocationType
    {

        private string locationUnitIdField;

        private int agentNumberField;

        private bool agentNumberFieldSpecified;

        private string expeditionField;

        private string countryCodeField;

        /// <remarks/>
        public string LocationUnitId
        {
            get
            {
                return this.locationUnitIdField;
            }
            set
            {
                this.locationUnitIdField = value;
            }
        }

        /// <remarks/>
        public int AgentNumber
        {
            get
            {
                return this.agentNumberField;
            }
            set
            {
                this.agentNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AgentNumberSpecified
        {
            get
            {
                return this.agentNumberFieldSpecified;
            }
            set
            {
                this.agentNumberFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Expedition
        {
            get
            {
                return this.expeditionField;
            }
            set
            {
                this.expeditionField = value;
            }
        }

        /// <remarks/>
        public string CountryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:posten.no/eConnect/OperationList")]
    public partial class AddressType
    {

        private string streetNameField;

        private string streetNumberField;

        private string postalCodeField;

        private string postalNameField;

        private string countryCodeField;

        /// <remarks/>
        public string StreetName
        {
            get
            {
                return this.streetNameField;
            }
            set
            {
                this.streetNameField = value;
            }
        }

        /// <remarks/>
        public string StreetNumber
        {
            get
            {
                return this.streetNumberField;
            }
            set
            {
                this.streetNumberField = value;
            }
        }

        /// <remarks/>
        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }

        /// <remarks/>
        public string PostalName
        {
            get
            {
                return this.postalNameField;
            }
            set
            {
                this.postalNameField = value;
            }
        }

        /// <remarks/>
        public string CountryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:posten.no/eConnect/OperationList")]
    public partial class StopType
    {

        private string stopIdField;

        private string stopSequenceField;

        private string locationIdField;

        private string customerNumberField;

        private string stopNameField;

        private AddressType addressField;

        private string phoneNumberField;

        private string customerContactField;

        private LocationType ownerLocationField;

        private MapCoordinate gpsPositionField;

        private System.DateTime earliestStopTimeField;

        private bool earliestStopTimeFieldSpecified;

        private System.DateTime latestStopTimeField;

        private bool latestStopTimeFieldSpecified;

        private string descriptionField;

        private string additionalInfoField;

        private ActionType actionTypeField;

        private bool actionTypeFieldSpecified;

        private bool repositioningField;

        private bool repositioningFieldSpecified;

        /// <remarks/>
        public string StopId
        {
            get
            {
                return this.stopIdField;
            }
            set
            {
                this.stopIdField = value;
            }
        }

        /// <remarks/>
        public string StopSequence
        {
            get
            {
                return this.stopSequenceField;
            }
            set
            {
                this.stopSequenceField = value;
            }
        }

        /// <remarks/>
        public string LocationId
        {
            get
            {
                return this.locationIdField;
            }
            set
            {
                this.locationIdField = value;
            }
        }

        /// <remarks/>
        public string CustomerNumber
        {
            get
            {
                return this.customerNumberField;
            }
            set
            {
                this.customerNumberField = value;
            }
        }

        /// <remarks/>
        public string StopName
        {
            get
            {
                return this.stopNameField;
            }
            set
            {
                this.stopNameField = value;
            }
        }

        /// <remarks/>
        public AddressType Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        public string PhoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }

        /// <remarks/>
        public string CustomerContact
        {
            get
            {
                return this.customerContactField;
            }
            set
            {
                this.customerContactField = value;
            }
        }

        /// <remarks/>
        public LocationType OwnerLocation
        {
            get
            {
                return this.ownerLocationField;
            }
            set
            {
                this.ownerLocationField = value;
            }
        }

        /// <remarks/>
        public MapCoordinate GpsPosition
        {
            get
            {
                return this.gpsPositionField;
            }
            set
            {
                this.gpsPositionField = value;
            }
        }

        /// <remarks/>
        public System.DateTime EarliestStopTime
        {
            get
            {
                return this.earliestStopTimeField;
            }
            set
            {
                this.earliestStopTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EarliestStopTimeSpecified
        {
            get
            {
                return this.earliestStopTimeFieldSpecified;
            }
            set
            {
                this.earliestStopTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime LatestStopTime
        {
            get
            {
                return this.latestStopTimeField;
            }
            set
            {
                this.latestStopTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatestStopTimeSpecified
        {
            get
            {
                return this.latestStopTimeFieldSpecified;
            }
            set
            {
                this.latestStopTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string AdditionalInfo
        {
            get
            {
                return this.additionalInfoField;
            }
            set
            {
                this.additionalInfoField = value;
            }
        }

        /// <remarks/>
        public ActionType ActionType
        {
            get
            {
                return this.actionTypeField;
            }
            set
            {
                this.actionTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionTypeSpecified
        {
            get
            {
                return this.actionTypeFieldSpecified;
            }
            set
            {
                this.actionTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool Repositioning
        {
            get
            {
                return this.repositioningField;
            }
            set
            {
                this.repositioningField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RepositioningSpecified
        {
            get
            {
                return this.repositioningFieldSpecified;
            }
            set
            {
                this.repositioningFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:posten.no/eConnect/OperationList")]
    public enum ActionType
    {

        /// <remarks/>
        P,

        /// <remarks/>
        D,

        /// <remarks/>
        PD,

        /// <remarks/>
        Unspecified,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:posten.no/eConnect/OperationList")]
    public partial class OperationListStop
    {

        private StopType stopInformationField;

        private PlannedOperationType[] plannedOperationField;

        private string statusField;

        private string externalTripIdField;

        private string routeField;

        private string tripIdField;

        private OperationListStopAlystraBexOrderLevel alystraBexOrderLevelField;

        /// <remarks/>
        public StopType StopInformation
        {
            get
            {
                return this.stopInformationField;
            }
            set
            {
                this.stopInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PlannedOperation")]
        public PlannedOperationType[] PlannedOperation
        {
            get
            {
                return this.plannedOperationField;
            }
            set
            {
                this.plannedOperationField = value;
            }
        }

        /// <remarks/>
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public string ExternalTripId
        {
            get
            {
                return this.externalTripIdField;
            }
            set
            {
                this.externalTripIdField = value;
            }
        }

        /// <remarks/>
        public string Route
        {
            get
            {
                return this.routeField;
            }
            set
            {
                this.routeField = value;
            }
        }

        /// <remarks/>
        public string TripId
        {
            get
            {
                return this.tripIdField;
            }
            set
            {
                this.tripIdField = value;
            }
        }

        /// <remarks/>
        public OperationListStopAlystraBexOrderLevel AlystraBexOrderLevel
        {
            get
            {
                return this.alystraBexOrderLevelField;
            }
            set
            {
                this.alystraBexOrderLevelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:posten.no/eConnect/OperationList")]
    public partial class OperationListStopAlystraBexOrderLevel
    {

        private PdaGoods[] goodsItemField;

        private PdaVas[] vasItemField;

        private PdaDeviation[] deviationItemField;

        private OperationListStopAlystraBexOrderLevelStopSortingItem[] stopSortingItemField;

        private OperationListStopAlystraBexOrderLevelOrderInfo[] orderInfoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GoodsItem")]
        public PdaGoods[] GoodsItem
        {
            get
            {
                return this.goodsItemField;
            }
            set
            {
                this.goodsItemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VasItem")]
        public PdaVas[] VasItem
        {
            get
            {
                return this.vasItemField;
            }
            set
            {
                this.vasItemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DeviationItem")]
        public PdaDeviation[] DeviationItem
        {
            get
            {
                return this.deviationItemField;
            }
            set
            {
                this.deviationItemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StopSortingItem")]
        public OperationListStopAlystraBexOrderLevelStopSortingItem[] StopSortingItem
        {
            get
            {
                return this.stopSortingItemField;
            }
            set
            {
                this.stopSortingItemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrderInfo")]
        public OperationListStopAlystraBexOrderLevelOrderInfo[] OrderInfo
        {
            get
            {
                return this.orderInfoField;
            }
            set
            {
                this.orderInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:posten.no/eConnect/OperationList")]
    public partial class OperationListStopAlystraBexOrderLevelStopSortingItem
    {

        private string stopPlaceIdField;

        private string orderStopIdItemField;

        /// <remarks/>
        public string StopPlaceId
        {
            get
            {
                return this.stopPlaceIdField;
            }
            set
            {
                this.stopPlaceIdField = value;
            }
        }

        /// <remarks/>
        public string OrderStopIdItem
        {
            get
            {
                return this.orderStopIdItemField;
            }
            set
            {
                this.orderStopIdItemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:posten.no/eConnect/OperationList")]
    public partial class OperationListStopAlystraBexOrderLevelOrderInfo
    {

        private string orderIDField;

        private string customerNameField;

        private string customerPhoneField;

        private string orderReferenceField;

        private string customerReferenceField;

        private string driverInformationField;

        /// <remarks/>
        public string OrderID
        {
            get
            {
                return this.orderIDField;
            }
            set
            {
                this.orderIDField = value;
            }
        }

        /// <remarks/>
        public string CustomerName
        {
            get
            {
                return this.customerNameField;
            }
            set
            {
                this.customerNameField = value;
            }
        }

        /// <remarks/>
        public string CustomerPhone
        {
            get
            {
                return this.customerPhoneField;
            }
            set
            {
                this.customerPhoneField = value;
            }
        }

        /// <remarks/>
        public string OrderReference
        {
            get
            {
                return this.orderReferenceField;
            }
            set
            {
                this.orderReferenceField = value;
            }
        }

        /// <remarks/>
        public string CustomerReference
        {
            get
            {
                return this.customerReferenceField;
            }
            set
            {
                this.customerReferenceField = value;
            }
        }

        /// <remarks/>
        public string DriverInformation
        {
            get
            {
                return this.driverInformationField;
            }
            set
            {
                this.driverInformationField = value;
            }
        }
    }
}
